import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Prism from "@/components/Prism";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.heading}>Hello</h1>
        <p className={styles.description}>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos
          quisquam soluta modi est totam consectetur. Error magni fugit velit
          provident quos, voluptas beatae repellendus dolores optio sapiente
          harum obcaecati expedita aliquam quis in maxime distinctio
          perspiciatis iste. Illo, odio velit?
        </p>
        <Prism />
      </main>
    </>
  );
}
